### ISSUE TITLE
Feature Request: Camel-to-Pascal Support?

### ISSUE THREAD

**Issue by adamholdenyall** [moh-hassan/odata2poco#1]
Would it be possible to support the Pascal Casing of Camel Case properties in the edmx? For instance if you have an edmx with a entity type of Person and properties email, firstName, lastName, and login, the C# that will be generated would be as such:

```
public class Person
{
        public Person();

        public string email { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string login { get; set; }
}
```

However, many C# coding standards desire properties to be pascal-cased, not camel cased. JSON.NET supports adding an attribute to a class that preserves the original camelCased property name.

So would it be possible to get an option added to the PocoSettings/command line argument that would generate the following instead?

```
public class Person
{
        public Person();

        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }
        [JsonProperty(PropertyName = "firstName")]
        public string FirstName { get; set; }
        [JsonProperty(PropertyName = "lastName")]
        public string LastName { get; set; }
        [JsonProperty(PropertyName = "login")]
        public string Login { get; set; }
}
```

**Comment by moh-hassan** [comment]
Welcome. 
I need to set some time aside to investigate and I plan to add the feature in the next release.

**Comment by moh-hassan** [comment]
Welcome.
It's possible to add an option  pascal-cased, with Json attributes in  the PocoSettings/command line argument.
I need to set some time aside to investigate and I plan to add the feature in the next release.
I will inform you as the feature is released.

**Comment by moh-hassan** [comment]
Hi adamholdenyall,
I'm glad to publish the new version of  OData2Poco.CommandLine 2.2.0  with support of your Feature Request #1: **Camel-to-Pascal Support**  and also **JsonProperty** support 

The new options are:
**Camel/Pas Support**
              -c --case  <camel> or <pas>
camel to convert Name of properties to camelcase
pas to convert to PascalCase
The default is the name as is.

**JsonProperty Support**
               -j to add JsonProperty

**example:**

                 o2pgen -v -j -c camel  -r http://services.odata.org/V4/Northwind/Northwind.svc -f north.cs

**sample output:**

		  public class product1
			   {
				[JsonProperty(PropertyName = "Id")]
				virtual public int id {get;set;} //PrimaryKey not null

				[JsonProperty(PropertyName = "Product_Name")]
				virtual public string productName {get;set;}

				[JsonProperty(PropertyName = "Category")]
				virtual public string category {get;set;}

				[JsonProperty(PropertyName = "Price")]
				virtual public decimal? price {get;set;}

			}   
You should install the package  Newtonsoft.Json to support JsonProperty. The generated code is compiled successfully.    
Give it a try and let me know your feedback of the new feature.
Thanks for support and welcome for any feature needed.
Best Regards,
Moh. Hassan
