### ISSUE TITLE
POCO compile errors

### ISSUE THREAD

**Issue by darinvanatta** [moh-hassan/odata2poco#12]
Hi,

I've added the generated POCO class to my project for the first time and getting a lot of compile errors due to 2 issues.  

The first issue is values are key words:

![image](https://user-images.githubusercontent.com/3100647/53361311-5457fa80-38ec-11e9-86ea-2a8fd585c842.png)

If you could add "@" in front of key words that will fix it

![image](https://user-images.githubusercontent.com/3100647/53361455-a567ee80-38ec-11e9-9534-33e640bd9f16.png)

The second is due to "members  name cannot be the same as enclosing type"
![image](https://user-images.githubusercontent.com/3100647/53360872-8ddc3600-38eb-11e9-8c2f-50eafb61795d.png)

The only resolution I can find is if the member and class name are the same then your codes changes the member name but I hate that solution. Any ideas?

Thanks

**Comment by moh-hassan** [comment]
I review the metadata xml and find char is included in the Units EnumType
		
		<EnumType Name="Units">
        <Member Name="mm" Value="0">
          <Annotation Term="Microsoft.Dynamics.OData.Core.V1.LabelId" String="mm" />
        </Member>
        <Member Name="cm" Value="1">
          <Annotation Term="Microsoft.Dynamics.OData.Core.V1.LabelId" String="cm" />
        </Member>
        <Member Name="pt" Value="2">
          <Annotation Term="Microsoft.Dynamics.OData.Core.V1.LabelId" String="pt" />
        </Member>
        <Member Name="char" Value="3">
          <Annotation Term="Microsoft.Dynamics.OData.Core.V1.LabelId" String="char" />
        </Member>
        <Member Name="Inch" Value="4">
          <Annotation Term="Microsoft.Dynamics.OData.Core.V1.LabelId" String="Inch" />
        </Member>
      </EnumType>

Because char is a reserved keyword in c#, it's expected for a compilation error in c#. 
But in VB.net, it's accepted by the compiler.

You suggest adding @ in front of such keywords. 
 Also if the first char is upperCase can solve the issue.
 So the resolution is giving the user choice either adding @ in front of the word  or Convert the first char to Upper (for any reserved keyword)
 
 For Applicant class, I find that the property is the same name as its  class	  
	
		<EntityType Name="Applicant">
        <Key>
          <PropertyRef Name="Applicant" />
        </Key>
        <Property Name="Applicant" Type="Edm.String" Nullable="false">
          <Annotation Term="Microsoft.Dynamics.OData.Core.V1.LabelId" String="@SYS30003" />
          <Annotation Term="Microsoft.Dynamics.OData.Core.V1.AllowEdit" Bool="false" />
          <Annotation Term="Microsoft.Dynamics.OData.Core.V1.AXType">
            <EnumMember>Microsoft.Dynamics.OData.Core.V1.AXType/String</EnumMember>
          </Annotation>
        </Property>
        <Property Name="AddressState" Type="Edm.String">
          <Annotation Term="Microsoft.Dynamics.OData.Core.V1.LabelId" String="@SYS323506" />
          <Annotation Term="Microsoft.Dynamics.OData.Core.V1.AXType">
            <EnumMember>Microsoft.Dynamics.OData.Core.V1.AXType/String</EnumMember>
          </Annotation>
        </Property>
		.....

So, the solution
1)add _ (underscore to the property in first /or the last

          _Applicant  or Applicant_
2) change the case of first char lowercase:   `applicant`

I  think this special handling should be done for  c# code not for vb.net code generation
What is your suggestion based on the above said

**Comment by darinvanatta** [comment]
Changing to lowercase seems like the best option.

Thanks!

**Comment by darinvanatta** [comment]
I just realized I missed your comment on upper casing key words will work. I like that better than adding the @ character.

**Comment by moh-hassan** [comment]
I  resolved the issue as you suggested:

- Upper casing the reserved key word for enum elements.
- Also, I resolved the issue of member name can not be the same as  enclosing type by  lower casing the first character.

The generated c# code is now free of compilation errors.

**Comment by darinvanatta** [comment]
Awesome!

Can you post an updated executable like you did last time so I can give it a try?

**Comment by moh-hassan** [comment]
Yes, Have a look to the attached file
[test.zip](https://github.com/moh-hassan/odata2poco/files/2906147/test.zip)

**Comment by darinvanatta** [comment]
No errors!  Thanks!

**Comment by moh-hassan** [comment]
Thanks :) :)
