### ISSUE TITLE
Not Null Members

### ISSUE THREAD

**Issue by darinvanatta** [moh-hassan/odata2poco#13]
Hi,

Currently members that cannot be null have the "not null" comment beside them: 

![image](https://user-images.githubusercontent.com/3100647/53419993-c59cb980-398f-11e9-8322-591875c8accd.png)

I have to programatically determine not nulls members to ensure my users enter a value for them but I don't see a way to do it with the comment.

Could a "[Not Null]" annotation or something similar be added that could be used to programatically determine if a member cannot be null?

Thanks

**Comment by darinvanatta** [comment]
It appears there is a "JsonPropertyAttribute required" which might be a good option

![image](https://user-images.githubusercontent.com/3100647/53420304-68edce80-3990-11e9-88b8-47bc5c8d7028.png)

**Comment by darinvanatta** [comment]
There is a RequriedAttribute Class which might be a better option

https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.requiredattribute?view=netframework-4.7.2


![image](https://user-images.githubusercontent.com/3100647/53420628-faf5d700-3990-11e9-85a4-dabd29cea621.png)


![image](https://user-images.githubusercontent.com/3100647/53420545-dac61800-3990-11e9-9ec2-16f5f54fa62a.png)

**Comment by darinvanatta** [comment]
Here's a good explanation of adding custom attributes and then verifying them with reflection:

https://www.c-sharpcorner.com/article/creating-and-using-custom-attributes-in-C-Sharp/

**Comment by moh-hassan** [comment]
You can add the required attribute: [Required]  by the option:

                -a req
There are  8 attributes you can add by the option -a 

                  -a, --attribute     Attributes, Allowed values: key, req,  json, tab, dm, proto, db, display        
Try it and let me if it achieve what you want.

**Comment by darinvanatta** [comment]
Perfect! I should have known you had already thought of everything.

**Comment by moh-hassan** [comment]
Thanks and Welcome.

**Comment by moh-hassan** [comment]
There is option that add '?' to the type for nullable data type:

             -b, --nullable      Add nullable data types
Which can generate for nullable data types:

                public double? Price {get;set;}
               
This option help for programmatically determine nullable  members

**Comment by darinvanatta** [comment]
Very cool! Thanks
