### ISSUE TITLE
OData2Poco Class library

### ISSUE THREAD

**Issue by darinvanatta** [moh-hassan/odata2poco#14]
I'm trying to understand how to use the project as a library.

I see this comment on the project page but it appears an image is missing

![image](https://user-images.githubusercontent.com/3100647/53447885-0b2aa800-39cb-11e9-8b75-6edf9f149d03.png)

I can't find anything else. Are you saying it's compile it to a dll and use it that way?

**Comment by moh-hassan** [comment]
OData2Poco  is a class library project compiled to dll and referenced by o2pgen /dotnet-o2pgen

**Comment by moh-hassan** [comment]
I generated the class library OData2Poco as a nuget package.
You can try it from the download in [github](https://github.com/moh-hassan/odata2poco/releases/download/3.1.0.358/OData2Poco.3.1.0.nupkg).
A new demo [project ](https://github.com/moh-hassan/odata2poco/tree/oauth2/OData2Poco.Demo)is added to the repository to show how to use OData2Poco  programmatically.
Also, a T4 template is available in the demo.
Let me know for any help  needed.

**Comment by darinvanatta** [comment]
That demo project is just what I was looking for!

I'm getting a compile error after downloading the latest: "Enabling license acceptance requires a license url"

![image](https://user-images.githubusercontent.com/3100647/53744473-bff91500-3e62-11e9-8130-dc9957fa717c.png)

**Comment by moh-hassan** [comment]
I disabled  license acceptance
Download a new version [3.1.0.360](https://github.com/moh-hassan/odata2poco/releases/download/3.1.0.360/OData2Poco.3.1.0.nupkg)
The demo as a [zip file](https://github.com/moh-hassan/odata2poco/releases/download/3.1.0.360/OData2Poco.Demo.zip)

**Comment by darinvanatta** [comment]
Any ideas on this error?

![image](https://user-images.githubusercontent.com/3100647/53761752-e5e6df80-3e8b-11e9-8b78-f20019d20a35.png)

**Comment by moh-hassan** [comment]
Steps to use the class library in the demo:
- Download from [github ](https://github.com/moh-hassan/odata2poco/releases/download/3.1.0.360/OData2Poco.3.1.0.nupkg)(it's not yet published to nuget Gallery, so use it as a local package)
- Define a local source for packages e.g, in `F:\nuget_local` using the [Package Manager console](https://codurance.com/2015/05/04/creating-a-local-nuget-repository/).  
-Add the package to the local source by the command `nuget add`  (modify the path in the command:

                  nuget add G:\local_nuget/OData2Poco.3.1.0.nupkg -Source F:\nuget_local

Then you you get:
>Installing OData2Poco 3.1.0.Successfully added package 'G:\local_nuget/OData2Poco.3.1.0.nupkg' to feed 'F:\nuget_local'.
- Be sure to activate only the local source in the package Manager console(to avoid download from nuget Gallery).

-Install the package by  the command:

     install-package OData2Poco 

- You find the package is added to your csproj file.

**Comment by moh-hassan** [comment]
Also, There is a direct simple way,
 The package is a zip file. You can unzip OData2Poco.3.1.0.nupkg and reference the dll from the lib folder (select net45/net461 or nestandard2)

**Comment by darinvanatta** [comment]
That is a much simpler way.

It worked great without auth2 but error when I try auth2. Am I setting the values correctly?

![image](https://user-images.githubusercontent.com/3100647/53766204-d53c6680-3e97-11e9-8763-b89e394387e2.png)

**Comment by moh-hassan** [comment]
set ServiceUrl

          ServiceUrl="https://con813-crm612cf723bbf35af6devaos.cloudax.dynamics.com/data"

I think it may be worked without oauth2 because you have already logged in to the service. Try it from other client (not logged in before).

**Comment by darinvanatta** [comment]
It got further....

![image](https://user-images.githubusercontent.com/3100647/53767962-0ff4cd80-3e9d-11e9-8160-19b8cbe5fb6e.png)

**Comment by moh-hassan** [comment]
I try in my side, but it seem that the service isn't available. I can't connect?

**Comment by darinvanatta** [comment]
Yes... I didn't notice the VM shut down on it's schedule. I re-started the VM and it ran for quite a while and then this message.

![image](https://user-images.githubusercontent.com/3100647/53768995-23556800-3ea0-11e9-832e-712cfdf880b3.png)

**Comment by moh-hassan** [comment]
It's working in my side using oauth2 and token 
Try it.

**Comment by darinvanatta** [comment]
Success! Thank you.

**Comment by moh-hassan** [comment]
Glad that you succeeded.
Best regards;

**Comment by moh-hassan** [comment]
Odata2Poco Class library v3.1.0 is published and available in nuget Gallery for [download](https://www.nuget.org/packages/OData2Poco/)
