### ISSUE TITLE
'Time' class. Undefined class.  #Bug

### ISSUE THREAD

**Issue by lobster2012-user** [moh-hassan/odata2poco#18]
I got 'Time' class of property.
Is it 'TimeSpan'?

**Comment by moh-hassan** [comment]
Welcome To Odata2Poco Project.
Can you show me the fragment of the generated c# code, so I can know the issue?

**Comment by lobster2012-user** [comment]
Thank you! 
Public Time PropertyName {get;set;}

Edmx : Type = EDM.TIME (sharepoint service)

(I writr shortly from mibile, sorry)

**Comment by moh-hassan** [comment]
It seems that it is OData  service V2. Is it ?

EDM.TIME in that case can be converted to TimeSpan
Can you confirm me the version of Odata service(V2).  
It's shown when you run o2pgen.

**Comment by lobster2012-user** [comment]
Plus 1 issue. Tool does not support default proxy. I downloaded manually metadata file. Where can i see version?

**Comment by moh-hassan** [comment]
In the header of the  xml file, Something like this:

                    <edmx:Edmx Version="1.0" xmlns:edmx="http://schemas.microsoft.com/ado/2007 /06/edmx">
            <edmx:DataServices xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" 
                    m:DataServiceVersion="2.0">

here **DataServiceVersion= 2.0**

**Comment by lobster2012-user** [comment]
3.0

**Comment by moh-hassan** [comment]
Thanks @lobster.
I will add `TimeSpan` data type as equivalent to `EDM.TIME` in the next release.
Also, Proxy will be supported too.

**Comment by lobster2012-user** [comment]
Thank you. I Will add separated issue about proxy and another one about overlapping properties.

**Comment by moh-hassan** [comment]
Hi @lobster
You can download the  new version  3.2.0 from [github ](https://github.com/moh-hassan/odata2poco/releases/download/3.2.0.1/O2Pgen.exe)
- fix EDM.TIME to TimeSpan
- Support Integrated windows Ntlm without credential.
- support Ntlm with windows credential and a separate domain option, example: 
       `-u user  -p password --domain my_AD_domain -o ntlm`
- support proxy with a new option, example:  
    `--proxy  http://myserver.com:8888`

Try it, and I appreciate your feedback.

**Comment by lobster2012-user** [comment]
Hi, @moh-hassan
Ntlm without credential for intranet+
Time +
Default ntlm proxy with config for internet+ (net framework)
