### ISSUE TITLE
Intranet requests  with NTLM Auth  #Feature

### ISSUE THREAD

**Issue by lobster2012-user** [moh-hassan/odata2poco#19]
Test at work. Intranet. SharePoint. Ntlm Auth. Failed. I will still test.

**Comment by lobster2012-user** [comment]
UseDefaultCredentials = True - solution (one of)

**Comment by moh-hassan** [comment]
Create a configuration file named: o2pgen.exe.config in the root of o2pgen.exe

Add the following xml text (with modifying **proxyaddress** **to your proxy and port** )

  		<?xml version="1.0" encoding="utf-8" ?>
		<configuration>
		  <system.net>
			<defaultProxy useDefaultCredentials="true" enabled="true">
			  <proxy usesystemdefault="false" autoDetect="false" proxyaddress="http://localhost:888" />
			</defaultProxy>
		  </system.net>
		</configuration>

Let me know if that is working
Post the error message

**Comment by lobster2012-user** [comment]
Connection failed with 127 888

**Comment by lobster2012-user** [comment]
The proxy in this case Is not used, it an intranet.

**Comment by moh-hassan** [comment]
Do you modify the  proxyaddress to your proxy server and port.
This value should match  the value in IE explorer.

**Comment by lobster2012-user** [comment]
This site in exceptions (in proxy settings)

**Comment by moh-hassan** [comment]
So, Proxy is not needed.

You are connected to the sharepoint service using your active directory credential user/password
for example:
user:  myuser@mydomain
password:******
Is it right?

**Comment by lobster2012-user** [comment]
Not quite, build-in Auth method, ntlm.  
I do not input my credentials.

**Comment by moh-hassan** [comment]
>I do not input my credentials.

I'm confused.

For NTLM connection, the parameter needed for http connection are:
username , password and  domain
Which I  suppose to implement it.

Intranet simply imply integrating Active directory security with all services for one single sign on.

When you are connecting from the mobile for example, you should pass credential and then they may be stored in your device for auto connection without re-entering the credential.

Did you try to connect to the service using curl/powershell or any Rest client tool? If so what is the http connection parameters to enter? Give me an example?

**Comment by lobster2012-user** [comment]
```csharp
//USE DEFAULT(WINDOW AUTH)CREDENTIALS for intranet.
var handler = new HttpClientHandler()
{
    UseDefaultCredentials = True
}
var http = new HttpClient(handler);
```
You only need this line or option, which will give the opportunity to set this flag.

I work inside the intranet, authentication is done by AD mechanisms without additional input of the login-password, since I am already logged in to the domain.
(Now I am writing from a mobile, later I can answer in more detail from a computer.)

**Comment by lobster2012-user** [comment]
Good evening (or another time of day).
I edited the code a bit. Is everything clear from my last post?

**Comment by moh-hassan** [comment]
Good evening
Thanks for code. It is clear and I will use it

**Comment by moh-hassan** [comment]
Can you try

           -u user -p password -0 basic

User and password are your login

**Comment by lobster2012-user** [comment]
I will try this tomorrow. I’m sure it will work, as my proxy exactly supports basic auth. Should I close the issue, this problem is not a critical bug? I am an ardent opponent of re-entering a password in AD, but this is just a matter of taste.

**Comment by moh-hassan** [comment]
It is nice if you can confirm it is working.
Taking into account proxy configuration using .config file.

**Comment by lobster2012-user** [comment]
Strange, received an authorization error. Although the heading was sent. While I’ll close the issue, I’ll make a separate version for myself so that authentication will be carried out by Windows.
