### ISSUE TITLE
MaxLength for a String property

### ISSUE THREAD

**Issue by darinvanatta** [moh-hassan/odata2poco#21]
Hi moh-hassan,

It's not an issue but a question: Are you aware of a way to get the maxlength of a string attribute?

It doesn't appear to be in the metadata but I hope I'm overlooking it.

Thanks

**Comment by moh-hassan** [comment]
Hi @darinvanatta 
Can you explain by example.
What do you mean by maxlength of a string attribute?
Do you mean:

             [MaxLength(50)]

**Comment by darinvanatta** [comment]
I'm writing the object values to a database. I'm dynamically creating the tables so when an property is a string, as shown in the image, I need to create a varchar field in the database but I don't if the string's max length is 5 characters or 5,000 characters.

![image](https://user-images.githubusercontent.com/3100647/56155898-9d8a0980-5f81-11e9-9d2c-e034669c8a0f.png)

Is there somewhere ODATA stores these max length values?

**Comment by moh-hassan** [comment]
I will investigate the maxlength of string in OData.

**Comment by darinvanatta** [comment]
Thank you!

The only thing I've found is this for Dynamics 365 Customer Engagement but doesn't apply to Finance and Operations:  https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/mt788314(v=crm.8)

**Comment by darinvanatta** [comment]
Here is the correct link: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/stringattributemetadata?view=dynamics-ce-odata-9

**Comment by moh-hassan** [comment]
I searched for `ContractPersonName` but i didn't find in the schema.
Is it the same schema previously processed or other one?

**Comment by darinvanatta** [comment]
It's another one but there isn't anything special about that class or attributes in my example.

I would need to determine the maxlength for any class attribute which is a string.

**Comment by moh-hassan** [comment]
I didn't find the maxlength in the schema, it seems that it's in not provided in the schema but odata v4 support it.
Can you check your schema if it  included the property maxlength .

**Comment by darinvanatta** [comment]
The metadata is showing v4 but I search for "maxlength" and don't find anything. Might there be another word used to search for?

![image](https://user-images.githubusercontent.com/3100647/56159548-96b3c480-5f8a-11e9-915e-ba2051128618.png)

You can see the metadata here:
https://con813-crm612cf723bbf35af6devaos.cloudax.dynamics.com/data/$metadata

**Comment by moh-hassan** [comment]
The schema also does not contain it.
I will investigate of  adding this feature.

**Comment by darinvanatta** [comment]
Thanks!

**Comment by moh-hassan** [comment]
Adding a new feature to support maxlength of string and binary (byte[] )
You can download the new version [v3.2.0.17](https://github.com/moh-hassan/odata2poco/releases/tag/3.2.0.17)

You can add the attribute [MaxLength(n)] by the option 

             -a max
			 
or programmatic

		new PocoSetting()
		{
		  Attributes = new List<string> {"max"}
		}

If the metadata schema of the service include the attribute MaxLength of value >0, then it will be generated as

        [MaxLength(30)]
        public string Title {get;set;}

**Comment by darinvanatta** [comment]
Awesome! Thanks
