### ISSUE TITLE
Support for read-only attributes from *.edmx 

### ISSUE THREAD

**Issue by dawiehyman** [moh-hassan/odata2poco#27]
I am attempting to create a poco from Microsoft Business Central, which is admittedly ODataV4 .  I am getting desperately close, except that some properties of entities in the Metadata is marked as read-only, but it comes into the generated poco with {get; set;} modifiers.  Is there a switch I am missing, or is this currently not supported?

**Comment by moh-hassan** [comment]
Welcome @dawiehyman to Odata2Poco project
Can you show me sample of the xml schema of Odata v4 service that support readonly properties?
You mean the generated property could be:

             public string  Name {get;}   //rather than {get;set;}

**Comment by moh-hassan** [comment]
A new package v3.3.0 is released that fix your issue.

The [new features](https://github.com/moh-hassan/odata2poco#what-is-new-in-v330):

You can download:
- Commandline console: [o2pgen](https://www.nuget.org/packages/OData2Poco.CommandLine/3.3.0)
- Dotnet core [tool](https://www.nuget.org/packages/OData2Poco.dotnet.o2pgen/3.3.0)
- class [library](https://www.nuget.org/packages/OData2Poco/3.3.0):

Try the commandline
```bash
o2pgen -r http://services.odata.org/V4/TripPinServiceRW -v 
```
You find the class with ReadOnly properties has get only.
```cs
public partial class Airline
	{
	    public string AirlineCode {get;} //PrimaryKey not null ReadOnly
	    public string Name {get;set;} // not null
	}
```
Let me know if that version fixes your issue.
