### ISSUE TITLE
Nullable DateTime

### ISSUE THREAD

**Issue by ceciliaritz** [moh-hassan/odata2poco#3]
Hi!

We find this tool very useful for generating models from our odata service. However, we would like to be able to generate a nullable DateTime property (using the -b option to the o2pgen command line tool).

As far as I understand DateTime is simply not included in the list of nullable data types.

Do you plan to address this in any future release?

**Comment by moh-hassan** [comment]
Hi ceciliaritz,
Thanks for your feature request of Nullable DateTime. 
 I'll add the feature in the next release. 
Best Regards,

**Comment by moh-hassan** [comment]
Hi ceciliaritz,
I release a new version 2.2.1 that support Nullable DateTime as you wish and also Nullable for DateTimeOffset, TimeSpan, Guid.
Give it a try.
Best Regards,

**Comment by ceciliaritz** [comment]
Thank you! I can confirm that it works perfectly for our DateTime properties.
/Cecilia

**Comment by moh-hassan** [comment]
Welcome 
Glad that it's working fine.
Best regards,
