### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by DavidRobinsonDk** [moh-hassan/odata2poco#34]
You should add the `max` attribute value option to the documentation. Both the readme, the wiki and the commandline output.
I had to dig into the code to find this, very useful, option.

**Comment by moh-hassan** [comment]
Thanks for suggestion. It will be added.

**Comment by moh-hassan** [comment]
A new page [Attribute Examples](https://github.com/moh-hassan/odata2poco/wiki/AttributeExamples) is added to wiki.
