### ISSUE TITLE
Feature Request: Add used options to output

### ISSUE THREAD

**Issue by DavidRobinsonDk** [moh-hassan/odata2poco#35]
I would find it very useful if the used options were recorded in the header of the output file.
Something along the lines of:

```
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated using  OData2Poco System.
//     Service Url: https://my.service.url/$metadata
//     MetaData Version: 4.0
//     Generated On: 2021-02-23T20:21:31
//     parameters: -f PocoFileName -a key req max -b
// </auto-generated>
//------------------------------------------------------------------------------
//
```

Also when using a local file with -r the "Service Url" part of this header is blank - it would be nice if that also contained the value of the -r parameter.

**Comment by moh-hassan** [comment]
Thanks for feedback. I'll add the feature to the plan of the next release.

**Comment by moh-hassan** [comment]
A new package [v3.5.0](https://www.nuget.org/packages/OData2Poco.CommandLine/3.5.0) is released and support the feature of adding used options to output and fix the filename.

**Comment by moh-hassan** [comment]
It's solved and the issue can be closed.
