### ISSUE TITLE
Possible to add field descriptions from metadata to C# output

### ISSUE THREAD

**Issue by rich0726** [moh-hassan/odata2poco#36]
Hello!  This is some awesome code.  Really efficient, and overwhelmingly accurate.  I have a question.  For the fields in my OData EDMX, I have descriptions that I'd eventually like to integrate into my data model.  Example:

        
        <Property Name="AboveGradeFinishedArea" Type="Edm.Decimal" Precision="14" Scale="2" />

As you can see, it provides additional informational details about properties in the OData API.  Is there a way to expose that in the exported POCOs?

**Comment by moh-hassan** [comment]
Thanks for suggestion.
Please  can you provide me with a sample of Edmx to check the  description field.
As I see  it is like a comment without title or annotation.

**Comment by rich0726** [comment]
Sure thing.  You can see the entire EDMX here:
https://raw.githubusercontent.com/RESOStandards/web-api-commander/e3ce8e276b0dd45a51c6087bb2498ad008150660/src/main/resources/RESODataDictionary-1.7.edmx

**Comment by moh-hassan** [comment]
Thanks for the sample data.
I investigated the file and find that every property has a `xml comment.` 
Odata2Poco use [OData standard V4](https://www.odata.org/documentation/) which ignore any comments. Normally [Annotation](http://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/odata-csdl-xml-v4.01.html#sec_Annotation)  is used to describe the extra data/information about any property/Entity.
So These comments can not be parsed or extracted by the library.

If your tool used to generated the EDMX file can generate data annotation instead if xml comments, then it can be added.

**Comment by moh-hassan** [comment]
The xml comments is outside the scope of OData V3/V4, and the issue can be closed.
