### ISSUE TITLE
How to deal with lookups in EDMX?

### ISSUE THREAD

**Issue by rich0726** [moh-hassan/odata2poco#37]
One more question: let's assume that I have a bunch of lookup fields in my data.  It doesn't appear that EntityFrameworkCore can handle scaffolding a database with anything other than generic types.  So if I instead of a primitive string, bool, or int, I have a data definition that is a List(Of <customType>), it doesn't know how to handle it.   Can the POCO classes generated by this library handle that somehow?

**Comment by moh-hassan** [comment]
Odata2Poco handle lookup as a navigation property. Use the option `-n  or --navigation` to generate navigation properties.
Example:
```
o2pgen -r http://services.odata.org/V4/Northwind/Northwind.svc/ -n
```
The model generated has a `Category` class with `Products` as a navigation property

```cs
public partial class Category
	{
	    public virtual int CategoryID {get;set;} //PrimaryKey not null
	    public virtual string CategoryName {get;set;} // not null
	    public virtual string Description {get;set;} 
	    public virtual byte[] Picture {get;set;} 
	    public virtual List<Product> Products {get;set;}  //Navigigation Property  List(Of )

	}
```

**Comment by rich0726** [comment]
Thanks, I tried that.  However, if I'm using code-first migrations to try to generate a database from those POCOs, it rejects anything that isn't a primitive, meaning all the navigation properties.

**Comment by moh-hassan** [comment]
Odat2Poco Generate Poco classes based on the standard OData V3/V4 that can be used with **OData Client tools**.
Using Poco classes in code-first migration need to build the Context class with Dbset<T> manually or using EF tools and overwrite the method `OnModelCreating` to handle the composite keys and Foreign keys.
Note also that Complex Entity is generated as a poco class without PK.
