### ISSUE TITLE
Support .NET 5+

### ISSUE THREAD

**Issue by charabaruk** [moh-hassan/odata2poco#38]
The dotnet-o2pgen tool does not run unless version 2.1.0 specifically of the .NET Core framework is installed. That means that even if one has .NET Core 3.x or .NET 5 or .NET 6 installed, the tool will not run until .NET Core 2.1.0 is installed. It is expected that the tool should be able to run on 2.1.0 *or newer* versions of the .NET Core framework, including .NET 5+.

**Comment by moh-hassan** [comment]
Thanks for suggestion.
I'll prepare a new version that support NET5 and excluding netcore 2.1.0

**Comment by moh-hassan** [comment]
Nuget package 4.0.0 is published supporting NET5.
