### ISSUE TITLE
Allow Headers in API Request

### ISSUE THREAD

**Issue by avidesk** [moh-hassan/odata2poco#42]
An OData API that I am using requires an API Key included as a header in the request. I don't see a way to provide this using the OData2POCO tool. Is this possible now, or could it be added as a feature?

**Comment by moh-hassan** [comment]
In o2pgen tool, an API Key  included as a header in the request. 

In case you are using '**Bearer Token'**, you can pass the token 'my_token' as :
```
-p my_token -o token
or
--password my_token --outh token
```

In case of '**Basic Auth'**,
```
  -u username -p password -o token
  
  or
  --user username --password mysecret --outh token
  ```
 for more details , [read](https://github.com/moh-hassan/odata2poco/wiki/authorize)

Let me know if this help to resolve your issue.

**Comment by moh-hassan** [comment]
@avidesk 
Did you tried the above comment and resolved your issue?

**Comment by moh-hassan** [comment]
Hi @avidesk 
A new release 6.0.0 is released with support  of a new option ```--http-header```  that  allow Headers in API Request  and many other features.
 
example:
```
o2pgen --url http://localhost/odata --auth none ^
--http-header "Authorization=Bearer %token%";key1=123;key2=abc
```
For more details: [read](https://github.com/moh-hassan/odata2poco/wiki/v6_0_0_how_to#New-Option-Allow-to-specify-Http-header-in-Odata-http-connection-with-the-computing-of-base64)
