### ISSUE TITLE
OpenType was not expected in the given context

### ISSUE THREAD

**Issue by kustanbruno** [moh-hassan/odata2poco#46]
I am using odata2poco with SAP Business One. The api of the SAP was updated since we last used the tool, and now we get the following error: 

`Error in executing the command: o2pgen --case none --filename poco.cs --auth none --url https://192.168.10.9:50000/b1s/v1/ --nullable
Error Message:
 Encountered the following errors when parsing the EDMX document:
UnexpectedXmlAttribute : The attribute 'OpenType' was not expected in the given context. : (3512, 44)
UnexpectedXmlAttribute : The attribute 'OpenType' was not expected in the given context. : (3579, 48)
UnexpectedXmlAttribute : The attribute 'OpenType' was not expected in the given context. : (3622, 46)
UnexpectedXmlAttribute : The attribute 'OpenType' was not expected in the given context. : (3716, 47)
UnexpectedXmlAttribute : The attribute 'OpenType' was not expected in the given context. : (3729, 48)
UnexpectedXmlAttribute : The attribute 'OpenType' was not expected in the given context. : (3778, 61)
UnexpectedXmlAttribute : The attribute 'OpenType' was not expected in the given context. : (3800, 51)
UnexpectedXmlAttribute : The attribute 'OpenType' was not expected in the given context. : (3813, 47)
UnexpectedXmlAttribute : The attribute 'OpenType' was not expected in the given context. : (3901, 56)`

The meta file is the following: 
[sap-metadata.xml.txt](https://github.com/moh-hassan/odata2poco/files/11262268/sap-metadata.xml.txt)

**Comment by moh-hassan** [comment]
I can't reproduce the error using o2pgen v5.0.1 with the attached xml file.
Please, can you check run o2pgen with the xml file 'sap-metadata.xml' to be sure of the error.
```
o2pgen --case none --filename poco.cs --auth none --url sap-metadata.xml --nullable 
```
In the other side, o2pgen  generate all open type Entities and the generated poco file is compiled without error.

**Comment by kustanbruno** [comment]
Thanks for the quick answer, we actually weren't using the generator with the meatadat xml. The url we provided returned the following json. This worked withe older version of the api. If we feed the xml url for the generator, everything works as expected. 

[metadata.json.txt](https://github.com/moh-hassan/odata2poco/files/11274161/metadata.json.txt)

**Comment by moh-hassan** [comment]
I tested o2pgen v5.0.1 with 2 services that support openType:
a) Microsoft graph at url:  https://graph.microsoft.com/v1.0   which have many openType entities.
b)The service https://services.odata.org/V4/OData/OData.svc/  which also has opentype .
All services are processed without errors at all.

Odata2Poco ignore the errors of xml parsing including `UnexpectedXmlAttribute` and continue processing all entities, but display the error for information.
It's supposed that the poco file is generated including all entities w/o opentype. Can you confirm this statement?
 Can you review the messages on the screen :
```
Number of Entities: xxx
Successfully Generated Poco Model
```

**Comment by moh-hassan** [comment]
Hi @kustanbruno ,
Please, can you send me the stack trace of the Exception to inspect it?

Also, Is the xml metafile generated from o2pgen? If not, kindly generate the xml file from within o2pgen.
That because, I tried to find the location of the error ,e.g, (3579, 48)  which is (line# , char position)  in the xml file and I find no relation between the location and the xml file. you can check it yourself.

**Comment by moh-hassan** [comment]
Hi @kustanbruno ,
A new release v6.0.0 is published that have many valuable features. For open type , I add a comment on the header of the class that show if the class is open type or complex/entity type. This comment help you if you want to add dynamic properties for the open type classes and have a complete information about the generated model.
