### ISSUE TITLE
Navigation properties missing

### ISSUE THREAD

**Issue by andresdsep** [moh-hassan/odata2poco#8]
As of the new pre-release version 3.0.0-RC1.240, navigation properties are missing from generated classes.

The xml:
``` xml
<EntityType Name="SomeClass">
    <NavigationProperty Name="Something" Type="AnotherClass"/>
</EntityType>
```

produces the following output:
``` c#
public class SomeClass
{
}
```

**Comment by moh-hassan** [comment]
Thanks for feedback.
Navigation properties are option and can be generated using the option -n
o2pgen -r url -n 
o2pgen --help  =>show all available options.
Try to add this option and let me know if  navigation properties exist.

**Comment by andresdsep** [comment]
You're absolutely right, was just missing the argument.
