### ISSUE TITLE
Support for .Net Core

### ISSUE THREAD

**Issue by TimoMeijer** [moh-hassan/odata2poco#9]

**Comment by moh-hassan** [comment]
Welcome @TimoMeijer in Odata2Poco project.
A new version is in progress for Support for .Net Core and publishing .NET Core Global Tool ( .NET Core 2.1 SDK and later versions).

**Comment by dannyweeks** [comment]
@moh-hassan when do you think this will be available? Thanks!

**Comment by moh-hassan** [comment]
@dannyweeks , Welcome To Odata2Poco Project.
I expect the .NET Core Global Tool ( dotnet-o2pgen) with  new features  may be available within ~ 10 days.
Best regards.

**Comment by moh-hassan** [comment]
Hi @TimoMeijer, @dannyweeks,
The new .NET Core dotnet Global tool [OData2Poco.dotnet.o2pgen ](https://github.com/moh-hassan/odata2poco/releases/tag/3.0.0.262)v3.0.0 is available now.
You can try it.

Download to a folder, and from there you can  install by the command

            dotnet tool update -g OData2Poco.dotnet.o2pgen  --add-source .:

To run:

               dotnet o2pgen -r https://services.odata.org/TripPinRESTierService -v

You use the same options as in the console o2pgen tool.
I appreciate  you if I can get your feedback before publishing to nuget server.

Best regards,

**Comment by moh-hassan** [comment]
OData2Poco.dotnet.o2pgen v3.0.3 have been published to [nuget](https://www.nuget.org/packages/OData2Poco.dotnet.o2pgen/3.0.3)

**Comment by moh-hassan** [comment]
You can open issue for any bug or feature required.
